require("user.keymaps")
require("user.options")
require("user.autocommands")
require("user.plugins")
require("user.treesitter")
require("user.cmp")
require("user.luasnip")
require("user.lsp")
require("user.neo-tree")
require("user.lualine")
require("user.telescope")
require("user.colorscheme")
-- require("user.colorpicker")
